### ISSUE TITLE
Few bugs

### ISSUE THREAD

**Issue by anyfactor** [bwasti/mebm#6]
Excellent tool. I have been using the tool extensively. This is my first time opening an issue in Github. Bugs -

* When the width of the picture is significantly larger than the height the picture gets distorted.
* Element scaling with scrolling isn't working properly with chrome
* Removing an element resulted in an undefined element which triggered an infinite loop leading firefox crushing and it had to remove every data and do re-install.
* Uploading time gets significantly lower after each new project

Nuances

* After adding an element you have to extend the timeline of the element first then move the element. Can't be done the other way around.
* No way to edit text after adding
* Need to add line space in texts
* Need to select element to move and modify them.

They are a few more bugs. I will try to provide screenshots later.

Thank you. Again excellent tool and very useful.

**Comment by bwasti** [comment]
Thanks for the report! I really appreciate it.

I'll get to the bugs as soon as I can.  Some clarification questions:

> Uploading time gets significantly lower after each new project

Does this mean you've created a video, deleted all the layers and are starting again with a new video?

> you have to extend the timeline of the element first then move the element

Are you trying increase the total time of the element beyond what is allocated for the project?  If so, I'm not sure the best way to expose this and would appreciate any suggestions :)

> No way to edit text after adding

If you click the text itself on the right you should be able to edit it.

**Comment by anyfactor** [comment]
I see you are working on audio. 🎉🎉

> Does this mean you've created a video, deleted all the layers and are starting again with a new video?

I have opened the site in incognito mode. After each use, I will close the browser. I will give you a comprehensive report after using it a few more times.

> Are you trying to increase the total time of the element beyond what is allocated for the project? If so, I'm not sure the best way to expose this and would appreciate any suggestions :)

https://user-images.githubusercontent.com/25797156/105806408-22ff7200-5fce-11eb-9341-cf9f6b25b218.mp4

> If you click the text itself on the right you should be able to edit it.

Got it. Thanks.

![image](https://user-images.githubusercontent.com/25797156/105806468-44605e00-5fce-11eb-8885-e8b2f74b899d.png)

**Comment by bwasti** [comment]
Yep, audio seems to be working (import, edit, and export on Firefox, safari and chrome has been tested)!

I think I've fixed a few bugs but I can't reproduce the following:

- chrome scroll to scale. It seems to work on my machine, would you be able to show me a screenshot or describe the result on your machine?
- firefox delete elements.  Never crashes for me.  Does it crash every time for you?

**Comment by anyfactor** [comment]
It was a one-time problem. Everything is working fine. I hope you continue to work on it. 🥂
